// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Traccar.Storage;

#nullable disable

namespace Traccar.Storage.Migrations.PostgreSQL.Migrations
{
    [DbContext(typeof(TraccarDbContext))]
    [Migration("20260721194840_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Traccar.Model.AgentDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentId")
                        .HasColumnType("text")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_name");

                    b.Property<string>("AgentPhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("agent_phone_number");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<int>("ResellerId")
                        .HasColumnType("integer")
                        .HasColumnName("reseller_id");

                    b.HasKey("Id")
                        .HasName("pk_agents");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("Traccar.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<double?>("DefaultLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("default_latitude");

                    b.Property<double?>("DefaultLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("default_longitude");

                    b.Property<int>("DeviceLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(110)
                        .HasColumnName("device_limit");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GoogleMapsApiKey")
                        .HasColumnType("text")
                        .HasColumnName("google_maps_api_key");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("MapProvider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("map_provider");

                    b.Property<string>("MapboxAccessToken")
                        .HasColumnType("text")
                        .HasColumnName("mapbox_access_token");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PrimaryColor")
                        .HasColumnType("text")
                        .HasColumnName("primary_color");

                    b.Property<string>("SecondaryColor")
                        .HasColumnType("text")
                        .HasColumnName("secondary_color");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Traccar.Model.Command", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attributes");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<bool>("TextChannel")
                        .HasColumnType("boolean")
                        .HasColumnName("text_channel");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_commands");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_commands_device_id");

                    b.ToTable("commands", (string)null);
                });

            modelBuilder.Entity("Traccar.Model.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attributes");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("disabled");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<long?>("PositionId")
                        .HasColumnType("bigint")
                        .HasColumnName("position_id");

                    b.Property<string>("SerialNo")
                        .HasColumnType("text")
                        .HasColumnName("serial_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unique_id");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_unique_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("Traccar.Model.DeviceAttribute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Attribute")
                        .HasColumnType("text")
                        .HasColumnName("attribute");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attributes");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<string>("Expression")
                        .HasColumnType("text")
                        .HasColumnName("expression");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_device_attributes");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_device_attributes_device_id");

                    b.ToTable("device_attributes", (string)null);
                });

            modelBuilder.Entity("Traccar.Model.DeviceModelInfo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Port")
                        .HasColumnType("text")
                        .HasColumnName("port");

                    b.HasKey("Id")
                        .HasName("pk_device_models");

                    b.ToTable("device_models", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manufacturer = "Xexun",
                            Model = "TK-103",
                            Port = "COM1"
                        },
                        new
                        {
                            Id = 2,
                            Manufacturer = "Concox",
                            Model = "GT-06",
                            Port = "COM2"
                        },
                        new
                        {
                            Id = 3,
                            Manufacturer = "Concox",
                            Model = "Concox JM01",
                            Port = "COM3"
                        },
                        new
                        {
                            Id = 4,
                            Manufacturer = "Teltonika",
                            Model = "Teltonika FMB920",
                            Port = "COM4"
                        });
                });

            modelBuilder.Entity("Traccar.Model.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attributes");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<DateTime?>("EventTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_time");

                    b.Property<long>("GeofenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("geofence_id");

                    b.Property<long>("MaintenanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("maintenance_id");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint")
                        .HasColumnName("position_id");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("DeviceId", "EventTime")
                        .HasDatabaseName("ix_events_device_id_event_time");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Traccar.Model.EventType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_event_types");

                    b.ToTable("event_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "General-purpose alarm with no specific category.",
                            Name = "general"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Emergency SOS alert triggered manually by the driver.",
                            Name = "sos"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Vibration or shock detected on the device or vehicle.",
                            Name = "vibration"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Unexpected vehicle movement detected while ignition is off.",
                            Name = "movement"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Vehicle speed dropped below the configured minimum threshold.",
                            Name = "lowspeed"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Vehicle speed exceeded the configured maximum threshold.",
                            Name = "overspeed"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Free-fall or sudden impact detected; used primarily on wearable and asset trackers.",
                            Name = "fallDown"
                        },
                        new
                        {
                            Id = 8,
                            Description = "External power supply voltage has fallen below the safe operating level.",
                            Name = "lowPower"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Internal battery charge is critically low.",
                            Name = "lowBattery"
                        },
                        new
                        {
                            Id = 10,
                            Description = "General device or vehicle fault condition reported.",
                            Name = "fault"
                        },
                        new
                        {
                            Id = 11,
                            Description = "External power supply to the tracker was disconnected.",
                            Name = "powerOff"
                        },
                        new
                        {
                            Id = 12,
                            Description = "External power supply to the tracker was reconnected.",
                            Name = "powerOn"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Door opened or closed unexpectedly.",
                            Name = "door"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Vehicle or asset lock was activated.",
                            Name = "lock"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Vehicle or asset lock was deactivated.",
                            Name = "unlock"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Geofence boundary was crossed (generic, direction unspecified).",
                            Name = "geofence"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Vehicle entered a defined geofence zone.",
                            Name = "geofenceEnter"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Vehicle exited a defined geofence zone.",
                            Name = "geofenceExit"
                        },
                        new
                        {
                            Id = 19,
                            Description = "GPS antenna cable has been cut or disconnected — possible tampering.",
                            Name = "gpsAntennaCut"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Collision or high-G impact detected.",
                            Name = "accident"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Vehicle is being towed while the ignition is off.",
                            Name = "tow"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Engine has been running with no movement for longer than the configured idle limit.",
                            Name = "idle"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Engine RPM exceeded the configured threshold.",
                            Name = "highRpm"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Sudden hard-acceleration event detected.",
                            Name = "hardAcceleration"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Sudden hard-braking event detected.",
                            Name = "hardBraking"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Sharp cornering or hard-turning manoeuvre detected.",
                            Name = "hardCornering"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Abrupt lane-change manoeuvre detected.",
                            Name = "laneChange"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Driver has exceeded continuous driving time beyond the configured fatigue limit.",
                            Name = "fatigueDriving"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Main power supply to the tracker was severed — likely tampering.",
                            Name = "powerCut"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Main power supply to the tracker was restored after a cut.",
                            Name = "powerRestored"
                        },
                        new
                        {
                            Id = 31,
                            Description = "GPS or GSM signal jamming detected in the vicinity.",
                            Name = "jamming"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Monitored temperature exceeded the configured high or low threshold.",
                            Name = "temperature"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Vehicle entered or exited a parking state.",
                            Name = "parking"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Vehicle bonnet (hood) was opened.",
                            Name = "bonnet"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Foot brake or parking brake was applied.",
                            Name = "footBrake"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Fuel level drop inconsistent with normal consumption — possible leak or theft.",
                            Name = "fuelLeak"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Physical tampering or device case opening detected.",
                            Name = "tampering"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Device is being removed from the vehicle.",
                            Name = "removing"
                        });
                });

            modelBuilder.Entity("Traccar.Model.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<double>("Altitude")
                        .HasColumnType("double precision")
                        .HasColumnName("altitude");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attributes");

                    b.Property<double>("Course")
                        .HasColumnType("double precision")
                        .HasColumnName("course");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<DateTime?>("DeviceTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("device_time");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<DateTime?>("FixTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fix_time");

                    b.Property<string>("GeofenceIds")
                        .HasColumnType("text")
                        .HasColumnName("geofence_ids");

                    b.Property<bool>("Ignition")
                        .HasColumnType("boolean")
                        .HasColumnName("ignition");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Network")
                        .HasColumnType("text")
                        .HasColumnName("network");

                    b.Property<double>("Odometer")
                        .HasColumnType("double precision")
                        .HasColumnName("odometer");

                    b.Property<bool>("Outdated")
                        .HasColumnType("boolean")
                        .HasColumnName("outdated");

                    b.Property<string>("Protocol")
                        .HasColumnType("text")
                        .HasColumnName("protocol");

                    b.Property<DateTime>("ServerTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("server_time");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision")
                        .HasColumnName("speed");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<bool>("Valid")
                        .HasColumnType("boolean")
                        .HasColumnName("valid");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasIndex("DeviceId", "FixTime")
                        .HasDatabaseName("ix_positions_device_id_fix_time");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("Traccar.Model.RouteInfo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("group_name");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<bool>("SupportsAdd")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_add");

                    b.Property<bool>("SupportsDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_delete");

                    b.Property<bool>("SupportsEdit")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_edit");

                    b.HasKey("Id")
                        .HasName("pk_routes");

                    b.ToTable("routes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupName = "General",
                            Label = "Fleet",
                            Path = "map",
                            SupportsAdd = false,
                            SupportsDelete = false,
                            SupportsEdit = false
                        },
                        new
                        {
                            Id = 2,
                            GroupName = "General",
                            Label = "Dashboard",
                            Path = "dashboard",
                            SupportsAdd = false,
                            SupportsDelete = false,
                            SupportsEdit = false
                        },
                        new
                        {
                            Id = 3,
                            GroupName = "General",
                            Label = "Geozones",
                            Path = "geozones",
                            SupportsAdd = true,
                            SupportsDelete = true,
                            SupportsEdit = true
                        },
                        new
                        {
                            Id = 4,
                            GroupName = "General",
                            Label = "Alerts",
                            Path = "alerts",
                            SupportsAdd = true,
                            SupportsDelete = true,
                            SupportsEdit = true
                        },
                        new
                        {
                            Id = 5,
                            GroupName = "General",
                            Label = "History",
                            Path = "trips",
                            SupportsAdd = false,
                            SupportsDelete = false,
                            SupportsEdit = false
                        },
                        new
                        {
                            Id = 6,
                            GroupName = "Administrative",
                            Label = "Users",
                            Path = "admin/users",
                            SupportsAdd = true,
                            SupportsDelete = true,
                            SupportsEdit = true
                        },
                        new
                        {
                            Id = 7,
                            GroupName = "Administrative",
                            Label = "Devices",
                            Path = "admin/devices",
                            SupportsAdd = true,
                            SupportsDelete = true,
                            SupportsEdit = true
                        },
                        new
                        {
                            Id = 8,
                            GroupName = "Administrative",
                            Label = "Move Devices",
                            Path = "admin/move-devices",
                            SupportsAdd = false,
                            SupportsDelete = false,
                            SupportsEdit = true
                        },
                        new
                        {
                            Id = 9,
                            GroupName = "Administrative",
                            Label = "SIM Cards",
                            Path = "admin/sim-cards",
                            SupportsAdd = true,
                            SupportsDelete = true,
                            SupportsEdit = true
                        },
                        new
                        {
                            Id = 10,
                            GroupName = "Administrative",
                            Label = "Clients",
                            Path = "admin/clients",
                            SupportsAdd = true,
                            SupportsDelete = true,
                            SupportsEdit = true
                        },
                        new
                        {
                            Id = 11,
                            GroupName = "Administrative",
                            Label = "Agents",
                            Path = "admin/agents",
                            SupportsAdd = true,
                            SupportsDelete = true,
                            SupportsEdit = true
                        },
                        new
                        {
                            Id = 12,
                            GroupName = "Administrative",
                            Label = "Resellers",
                            Path = "admin/resellers",
                            SupportsAdd = true,
                            SupportsDelete = true,
                            SupportsEdit = true
                        },
                        new
                        {
                            Id = 13,
                            GroupName = "Administrative",
                            Label = "Database",
                            Path = "admin/database",
                            SupportsAdd = false,
                            SupportsDelete = false,
                            SupportsEdit = false
                        });
                });

            modelBuilder.Entity("Traccar.Model.SimCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Imsi")
                        .HasColumnType("bigint")
                        .HasColumnName("imsi");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<int>("ResellerId")
                        .HasColumnType("integer")
                        .HasColumnName("reseller_id");

                    b.Property<long>("SerialNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("serial_number");

                    b.HasKey("Id")
                        .HasName("pk_sim_cards");

                    b.ToTable("sim_cards", (string)null);
                });

            modelBuilder.Entity("Traccar.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Administrator")
                        .HasColumnType("boolean")
                        .HasColumnName("administrator");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attributes");

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("disabled");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("text")
                        .HasColumnName("hashed_password");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked_out");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<bool>("Readonly")
                        .HasColumnType("boolean")
                        .HasColumnName("readonly");

                    b.Property<int?>("ResellerId")
                        .HasColumnType("integer")
                        .HasColumnName("reseller_id");

                    b.Property<string>("RouteAccess")
                        .HasColumnType("text")
                        .HasColumnName("route_access");

                    b.Property<string>("Salt")
                        .HasColumnType("text")
                        .HasColumnName("salt");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
